/* array of products here */
const movies = [
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genre: "Sci-Fi",
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    altText:
      "A man discovers the truth about his reality and fights a powerful system.",
    imgUrl: "",
  },
  {
    name: "Inception",
    releaseDate: "2010-07-16",
    genre: "Sci-Fi",
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    altText:
      "A skilled thief enters dreams to steal secrets but takes on a risky heist.",
    imgUrl: "",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genre: "Action",
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    altText: "Batman battles the Joker to protect Gotham City.",
    imgUrl: "",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genre: "Drama",
    actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    altText: "The story of a simple man's journey through history and love.",
    imgUrl: "",
  },
  {
    name: "Pulp Fiction",
    releaseDate: "1994-10-14",
    genre: "Crime",
    actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    altText: "Interwoven stories of crime in Los Angeles.",
    imgUrl: "",
  },
  {
    name: "Fight Club",
    releaseDate: "1999-10-15",
    genre: "Drama",
    actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    altText: "A disillusioned man starts an underground fight club.",
    imgUrl: "",
  },
  {
    name: "The Godfather",
    releaseDate: "1972-03-24",
    genre: "Crime",
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    altText: "A mafia family patriarch balances crime and family loyalty.",
    imgUrl: "",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genre: "Historical",
    actors: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
    altText: "A businessman saves Jewish lives during the Holocaust.",
    imgUrl: "",
  },
  {
    name: "The Shawshank Redemption",
    releaseDate: "1994-09-23",
    genre: "Drama",
    actors: ["Tim Robbins", "Morgan Freeman"],
    altText: "The story of friendship and hope in prison.",
    imgUrl: "",
  },
  {
    name: "The Silence of the Lambs",
    releaseDate: "1991-02-14",
    genre: "Thriller",
    actors: ["Jodie Foster", "Anthony Hopkins"],
    altText:
      "An FBI trainee seeks help from a serial killer to catch another killer.",
    imgUrl: "",
  },
  {
    name: "The Lord of the Rings: The Fellowship of the Ring",
    releaseDate: "2001-12-19",
    genre: "Fantasy",
    actors: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    altText: "A hobbit sets out on a quest to destroy a powerful ring.",
    imgUrl: "",
  },
  {
    name: "Jurassic Park",
    releaseDate: "1993-06-11",
    genre: "Adventure",
    actors: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
    altText: "Scientists visit an island with cloned dinosaurs.",
    imgUrl: "",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genre: "Action",
    actors: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    altText: "A Roman general seeks revenge after being betrayed.",
    imgUrl: "",
  },
  {
    name: "Avatar",
    releaseDate: "2009-12-18",
    genre: "Sci-Fi",
    actors: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    altText: "A soldier explores a lush alien world and its people.",
    imgUrl: "",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genre: "War",
    actors: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
    altText: "A group of soldiers embarks on a mission to save a paratrooper.",
    imgUrl: "",
  },
  {
    name: "Titanic",
    releaseDate: "1997-12-19",
    genre: "Romance",
    actors: ["Leonardo DiCaprio", "Kate Winslet"],
    altText: "A love story set aboard the ill-fated Titanic.",
    imgUrl: "",
  },
  {
    name: "Goodfellas",
    releaseDate: "1990-09-19",
    genre: "Crime",
    actors: ["Ray Liotta", "Robert De Niro", "Joe Pesci"],
    altText: "A young man rises through the ranks of the mob.",
    imgUrl: "",
  },
  {
    name: "Braveheart",
    releaseDate: "1995-05-24",
    genre: "History",
    actors: ["Mel Gibson", "Sophie Marceau"],
    altText: "The story of a Scottish rebel who fights for freedom.",
    imgUrl: "",
  },
  {
    name: "The Departed",
    releaseDate: "2006-10-06",
    genre: "Crime",
    actors: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
    altText: "An undercover cop and a mole in the police seek each other out.",
    imgUrl: "",
  },
  {
    name: "The Lion King",
    releaseDate: "1994-06-24",
    genre: "Animation",
    actors: ["Matthew Broderick", "James Earl Jones", "Jeremy Irons"],
    altText: "A young lion prince seeks to reclaim his throne.",
    imgUrl: "",
  },
];
